### ISSUE TITLE
new gvcci option

### ISSUE THREAD

**Issue by FabriceCastel** [nan0s7/ngvccixgogh#1]
Not quite an issue - but you asked for the ability not to copy every wallpaper into the `~/.gvcci/themes` dir to save on space and I've just added that. If you pass the `--symlink-wallpaper` param then it'll do what it sounds like! Symlink the wallpaper rather than copy it.

Thought you might find that useful :)

**Comment by nan0s7** [comment]
Awesome to hear! 

Thanks for letting me know! :D
